services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: admin_manager_pois_data
    env_file: .env
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings
    command: sh -c "
      python manage.py migrate
      && python manage.py loaddata adminuser.json
      && python manage.py collectstatic --noinput
      && gunicorn core.wsgi:application --bind 0.0.0.0:8000 --reload"
    expose:
      - 8000
    networks:
      - app-net
    volumes:
      - .:/backend
      - ./logs:/app/logs
      - staticfiles:/app/staticfiles
      - media:/app/media
    restart: on-failure
    stdin_open: true
    tty: true

  proxy:
    image: nginx:latest
    restart: always
    networks:
      - app-net
    ports:
      - 80:80
    volumes:
      - ./scripts/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./logs:/var/log/nginx
      - staticfiles:/app/staticfiles
      - media:/app/media
    depends_on:
      - backend

networks:
  app-net:
    driver: bridge

volumes:
  staticfiles:
  media:
