# Generated by Django 5.2.5 on 2025-09-03 13:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HistoricalImportData",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("csv", "CSV"), ("json", "JSON"), ("xml", "XML")],
                        db_index=True,
                        max_length=8,
                    ),
                ),
                ("filename", models.CharField(max_length=256)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Historical Import Data",
                "verbose_name_plural": "Historical Imports Data",
                "db_table": "historical_import_data",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="POI",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("external_id", models.CharField(db_index=True, max_length=128)),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("category", models.CharField(db_index=True, max_length=64)),
                ("ratings", models.JSONField(blank=True, default=list)),
                ("description", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Point Of Interest",
                "verbose_name_plural": "Point Of Interest",
                "db_table": "point_of_interest",
                "ordering": ["id"],
                "indexes": [
                    models.Index(
                        fields=["category"], name="point_of_in_categor_53d822_idx"
                    ),
                    models.Index(
                        fields=["external_id"], name="point_of_in_externa_96d9fb_idx"
                    ),
                ],
            },
        ),
    ]
